name: Generate-Golden-Image
run-name: ${{ github.actor}} has pushed to master, starting an image build.
on:
  push:
    branches:
      - "master"
jobs:
  BUILD-GOLDEN-RELEASE-IMAGE:
    runs-on: ubuntu-latest
    steps:
      - name: LOGIN TO AZURE
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Create App Baked Image
        id: imageBuilder
        uses: azure/build-vm-image@v0
        with:
          location: 'eastus2'
          resource-group-name: 'DEBIT-GithubActionsImageBuilder'
          managed-identity: 'GithubActions-ImageBuilder' # Managed identity
          source-os-type: 'windows'
          source-image-type: 'platformImage'
          source-image: MicrosoftWindowsServer:WindowsServer:2019-Datacenter:latest #unique identifier of source image
          dist-type: 'SharedImageGallery'
          dist-resource-id: '/subscriptions/a0cbc331-791e-4108-949b-89ea4df47e8e/resourceGroups/GitHub-ImageBuild/providers/Microsoft.Compute/galleries/GithubActions_ImageBuildGallery/images/G2VM-Windows10-Client/versions/0.1.${{ GITHUB.RUN_ID }}' #Replace with the resource id of your shared image  gallery's image definition
          dist-location: 'eastus'




          
